# Generated by Django 5.2.8 on 2025-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alxe_commance', '0003_alter_cart_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('BOOKS', 'Books'), ('HOME', 'Home & Kitchen'), ('TOYS', 'Toys & Games')], default='ELECTRONICS', max_length=50, null=True),
        ),
    ]
