# Generated by Django 5.2.8 on 2025-11-30 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alxe_commance', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
